### PR TITLE
Add Cloudwatch Log Groups

### PR DESCRIPTION
**Pull request by apolloclark**

### CODE REVIEW

**Comment by apolloclark** [comment]
I added a new AWS Resource attribute "attr_spec" It currently runs on every Cloudwatch Log Group during enumeration when \__init__ is called. Since these calls can return a lot of data, and may not always been required, should I instead implement it the same way as the tags() property?

**Comment by avram** [comment]
Are those additional attributes also addressable by their own ARNs, or are they only meaningful as details of the log group?

If they are generally needed to effectively work with a matched log group, I don't see any issue with loading the data when the group is initialized.

**Comment by apolloclark** [comment]
@avram No, those additional calls do not have dedicated ARNs. I think they were omitted from being always included in the default "describe_log_groups" call since they are optional settings, not used by default.

As for "needed to effectively work," that is debatable. Specifically I'm using skew for a security monitoring, alerting, reporting, and assessment, and need access to these additional details.

**Comment by avram** [comment]
I don't see any issue with including them.

**Comment by apolloclark** [comment]
Awesome, thanks! :) I'm going to open 2 more Pull Requests, which use this same pattern to retrieve additional information.

**Pull request merged**
