### PR TITLE
workaround "AttributeError: 'str' object has no attribute 'get'" error

### PR DESCRIPTION
**Pull request by mszabo**
I was trying to get your examples to run, but got AttributeError all the time. I guess it was because changes in botocore. I made it to work with this change. I am not sure if it's the correct fix for the problem, but it works for me this way.

### CODE REVIEW

**Comment by che2cbs** [comment]
Looks like botocore.config is borked somewhere and it's causing session.available_profile to return bogus results.
```
>>> pprint(session.full_config)
{'_path': '/Users/che2cbs/.aws/config',
 'profiles': {'_path': '/Users/che2cbs/.aws/credentials',
              'acct.': {'account_id': 'xxxxxxxxxx',
                      'aws_access_key_id': '<acct1_access_key>'',
                      'aws_secret_access_key': '<acc1_secret_key>',
                      'region': 'us-east-1'},
              'acct2': {'account_id': 'yyyyyyyyyy',
                          'aws_access_key_id': '<acct2_access_key>',
                          'aws_secret_access_key': '<acct2_secret_key>',
                          'region': 'us-east-1'}}}
```
session.full_config['profiles']['_path'] probably shouldn't be there.  Removing the credentials file and storing everything in config will also bypass this problem.

**Comment by garnaat** [comment]
What version of botocore are you using?

**Comment by che2cbs** [comment]
My previous session above was using botocore 0.79.0.  I just updated to 0.81.0 and it's still misbehaving:

```
>>> print botocore.session.__version__
0.81.0
>>> session.available_profiles
['acct1', 'acct2', '_path']
```

**Comment by mszabo** [comment]
I have 0.77.0 now, but as I remember I tried with the latest botocore before digging into the source code to make it work.

**Pull request closed without merging**
