### PR TITLE
Get rid of YAML warning

### PR DESCRIPTION
**Pull request by cameronezell**

### CODE REVIEW

**Comment by lhaig** [comment]
I was going to do this but now I just have to add +1 

Thanks @cameronezell

**Comment by avram** [comment]
@cameronezell @lhaig  This doesn't test cleanly -- can you look at #161 and the failures there?

Closing in favor of #161 so we can track the test status cleanly

**Comment by cameronezell** [comment]
@avram Hi, it looks like the FullLoader attribute isn't present in the PyYaml version specified in the requirements.txt file. I think bumping up that version should work or I could test just changing `safe_load` to `load` and see if it eliminates the error despite the missing attribute.

**Comment by avram** [comment]
Those all sound like viable solutions. Happy to merge and a release a working version of this fix. 👍

**Pull request closed without merging**
